name: Build lib and demo page Action
desctipion: "Build and test the lib and demo page"
inputs:
  stage:
    description: "Current stage"
    default: "beta"
    required: false
    type: string
  release_update_only:
    description: "Only update the release version"
    default: "false"
    required: false
    type: boolean
outputs:
  package_base_version:
    description: "Package main version related to given stage"
    value: v${{ steps.package-version.outputs.current-version }}
  package_version:
    description: "Package version related to given stage"
    value: v${{ steps.package-version.outputs.current-version }}-${{ inputs.stage }}
runs:
  using: "composite"
  steps:
    - name: Setup Node 18.x
      uses: actions/setup-node@v1
      with:
        node-version: "18.x"
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.3.1
    - name: BETA-PREVIEW build minified main css library, js plugins and demo in standalone mode
      if: ${{ inputs.stage != 'release' }}
      env:
        PACKAGE_VERSION: v${{ steps.package-version.outputs.current-version }}-${{ inputs.stage }}
      run: |
        npm install
        npm run lint
        npm run build:lib        
        parcel build --target demo --no-source-maps --no-content-hash --public-url ./v${{ steps.package-version.outputs.current-version }}-${{ inputs.stage }}
        npm run test --if-present
      shell: bash
    - name: "RELEASE - build minified main css library, js plugins and demo in standalone mode"
      if: ${{ inputs.stage == 'release' && inputs.release_update_only == 'false' }}
      env:
        PACKAGE_VERSION: v${{ steps.package-version.outputs.current-version }}
      run: |
        npm install
        npm run lint
        npm run build:lib         
        parcel build --target demo --no-source-maps --no-content-hash --public-url ./v${{ steps.package-version.outputs.current-version }}
        npm run test --if-present
      shell: bash
    - name: "RELEASE - update only release demo page"
      if: ${{ inputs.stage == 'release' && inputs.release_update_only == 'true' }}
      env:
        PACKAGE_VERSION: v${{ steps.package-version.outputs.current-version }}
      run: |
        npm install
        npm run lint
        npm run build:lib         
        parcel build --target demo --no-source-maps --no-content-hash --public-url ./
        npm run test --if-present
      shell: bash
